-- MySQL Script generated by MySQL Workbench
-- Thu Aug 15 17:12:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema financial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema financial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `financial` DEFAULT CHARACTER SET utf8 ;
USE `financial` ;

-- -----------------------------------------------------
-- Table `financial`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`user` (
  `user_id` BIGINT(255) NOT NULL AUTO_INCREMENT,
  `identity_num` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone_num` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `perms` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`article` (
  `article_id` BIGINT(255) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `summary` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `category` INT NULL,
  PRIMARY KEY (`article_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`collection` (
  `user_id` BIGINT(255) NOT NULL,
  `article_id` BIGINT(255) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`comment` (
  `id` BIGINT(255) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(255) NULL,
  `article_id` BIGINT(255) NULL,
  `content` VARCHAR(10000) NULL,
  `light_amount` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`light`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`light` (
  `user_id` BIGINT(255) NOT NULL,
  `comment_id` BIGINT(255) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`message` (
  `id` BIGINT(255) NOT NULL AUTO_INCREMENT,
  `time` DATE NULL,
  `user_id` BIGINT(255) NULL,
  `type` INT NULL,
  `content` VARCHAR(45) NULL,
  `is_read` TINYINT NULL,
  `is_delete` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`trade_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`trade_record` (
  `id` BIGINT(255) NOT NULL AUTO_INCREMENT,
  `trade_id` BIGINT(255) NULL,
  `create_time` DATE NULL,
  `complete_time` DATE NULL,
  `type` INT NULL,
  `code` INT NULL,
  `amount` FLOAT NULL,
  `price` FLOAT NULL,
  `total` FLOAT NULL,
  `user_id` BIGINT(255) NULL,
  `status` INT NULL,
  `is_customize` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`transfer_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`transfer_record` (
  `id` BIGINT(255) NOT NULL,
  `create_time` DATE NULL,
  `complete_time` DATE NULL,
  `sell_type` INT NULL,
  `buy_type` INT NULL,
  `user_id` BIGINT(255) NULL,
  `status` INT NULL,
  `is_customize` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`bond`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`bond` (
  `id` BIGINT(255) NOT NULL,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  `latest_price` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`card` (
  `user_id` VARCHAR(45) NULL,
  `cardnum` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`cash`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`cash` (
  `user_id` BIGINT(255) NOT NULL,
  `amount` FLOAT NULL,
  `percentage` FLOAT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`deposit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`deposit` (
  `user_id` BIGINT(255) NOT NULL,
  `amount` FLOAT NULL,
  `percentage` FLOAT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`deposit_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`deposit_product` (
  `id` BIGINT(255) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `rate` FLOAT NULL,
  `length` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`dom_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`dom_stock` (
  `id` BIGINT(255) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  `latest_price` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`for_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`for_stock` (
  `id` BIGINT(255) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  `latest_price` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`fund`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`fund` (
  `name` VARCHAR(45) NULL,
  `rate` FLOAT NULL,
  `time` DATE NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`gold`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`gold` (
  `id` BIGINT(255) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  `latest_price` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`ins_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`ins_product` (
  `id` BIGINT(255) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  `compensation` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`insurance` (
  `user_id` BIGINT(255) NOT NULL,
  `amount` FLOAT NULL,
  `percentage` FLOAT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`investment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`investment` (
  `user_id` BIGINT(255) NOT NULL,
  `amount` FLOAT NULL,
  `percentage` FLOAT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`my_bond`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`my_bond` (
  `user_id` BIGINT(255) NOT NULL,
  `code` VARCHAR(45) NULL,
  `purchase_price` FLOAT NULL,
  `profit` FLOAT NULL,
  `profit_rate` FLOAT NULL,
  `quantity` INT NULL,
  `amount` FLOAT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`my_depo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`my_depo` (
  `user_id` BIGINT(255) NOT NULL,
  `product_id` BIGINT(255) NULL,
  `amount` FLOAT NULL,
  `maturity` DATE NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`my_fund`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`my_fund` (
  `user_id` BIGINT(255) NOT NULL,
  `balance` FLOAT NULL,
  `update_time` DATE NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`my_gold`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`my_gold` (
  `user_id` BIGINT(255) NOT NULL,
  `code` VARCHAR(45) NULL,
  `purchase_price` FLOAT NULL,
  `profit` FLOAT NULL,
  `profit_rate` FLOAT NULL,
  `quantity` INT NULL,
  `amount` FLOAT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`my_ins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`my_ins` (
  `user_id` BIGINT(255) NOT NULL,
  `beneficiary` VARCHAR(45) NULL,
  `product_id` BIGINT(255) NULL,
  `maturity` DATE NULL,
  `price` FLOAT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`property` (
  `user_id` BIGINT(255) NOT NULL,
  `admin_id` BIGINT(255) NOT NULL,
  `view_type` VARCHAR(45) NULL,
  `pro_or_invest` VARCHAR(45) NULL,
  `asset_type` VARCHAR(45) NULL,
  `prefers` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financial`.`my_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financial`.`my_stock` (
  `user_id` BIGINT(255) NOT NULL,
  `code` VARCHAR(45) NULL,
  `purchase_price` FLOAT NULL,
  `profit` FLOAT NULL,
  `profit_rate` FLOAT NULL,
  `quantity` INT NULL,
  `amount` FLOAT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
