spring:
  datasource:
     url: jdbc:mysql://localhost:3306/financial?serverTimezone=CTT&characterEncoding=UTF-8
     username: root
     password: Nutter_438
     driver-class-name: com.mysql.cj.jdbc.Driver
     max-active: 200
     max-idle: 20
     min-idle: 10
  thymeleaf:
     cache: false
  jackson:
    time-zone: GMT+8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
      

mybatis:
  mapper-locations: classpath:dataImpl/*/*Mapper.xml

server:
  port: 3180

# python调用配置 #
python:
  dir: ""
